/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ConversationRecords {
  /** Open (or create) the records tables in `dbPath`. */
  static open(dbPath: string): Promise<ConversationRecords>
  get(conversationId: string): Promise<ConversationRecord | null>
  findBySession(provider: Provider, sessionId: string): Promise<ConversationRecord | null>
  /** Every record as a list row (active and deleted; filter on `status`). */
  listSummaries(): Promise<Array<RecordSummary>>
  create(input: NewRecord, at: number): Promise<CreateOutcome>
  setConfig(input: SetConfig, at: number): Promise<SetConfigOutcome>
  /** null = no such record. */
  setDone(conversationId: string, done: boolean, at: number): Promise<ConversationRecord | null>
  /** Tombstone. false = missing or already deleted. */
  markDeleted(conversationId: string, at: number): Promise<boolean>
  /** Remove the row (rollback of an unexposed creation). false = missing. */
  purge(conversationId: string): Promise<boolean>
  rekey(from: string, to: string): Promise<RekeyOutcome>
  setCurrentSession(conversationId: string, binding: SessionBinding, at: number): Promise<ConversationRecord | null>
  setCurrentSessionUsage(conversationId: string, sessionId: string, usage: ProviderTurnUsage, at: number): Promise<ConversationRecord | null>
  addSessionBinding(conversationId: string, binding: SessionBinding, at: number): Promise<ConversationRecord | null>
  appendBranchLaunch(conversationId: string, digest: string, handoff: string): Promise<BranchLaunchOutcome>
  /** Lease the first-message delivery to `token` (the caller's random UUID). null = not claimed. */
  claimInitialMessageDispatch(conversationId: string, token: string, at: number): Promise<ConversationRecord | null>
  /** null = `token` does not hold the lease, or the message was already delivered. */
  completeInitialMessageDispatch(conversationId: string, token: string, at: number): Promise<ConversationRecord | null>
}

export declare class Ingest {
  /**
   * Open (or create) the store at `dbPath`, bring it up to date with `roots`, and watch them.
   * Resolves after the initial scan is committed; `onChange` also fires during that scan.
   */
  static start(roots: Array<Root>, dbPath: string, onChange: ((arg: ChangeEvent) => void)): Promise<Ingest>
  /** The initial scan's counts and timing. */
  get initialScan(): ScanReport
  listSessions(options: ListOptions): Promise<SessionPage>
  session(sessionId: string): Promise<SessionRow | null>
  messages(sessionId: string, options: MessagesOptions): Promise<Array<Message>>
  /**
   * Provider-counted token usage of the turns in `[since, until)`, grouped by session, UTC day
   * or model, plus the latest Codex rate limits. Replaces `/api/usage`'s transcript parsers.
   */
  usage(query: UsageQuery): Promise<UsageReport>
  /**
   * The latest request's context for a native session id (the context meter), or null when no
   * transcript of that id records one. Replaces session-context.ts.
   */
  latestContext(sessionId: string): Promise<ContextReading | null>
  /**
   * Deep search: the newest listed messages (at most `limit`) whose text contains `query`, ASCII
   * case-insensitively. It scans the message table (~0.5-1 s on 290k messages), so it runs on
   * a connection of its own and never holds the reader that serves message pages.
   */
  search(query: string, limit: number): Promise<Array<SearchHit>>
  /** Stop watching and release `onChange` (so Node can exit). Idempotent. */
  stop(): Promise<void>
}

export type BranchLaunchOutcome =
  | { t: 'recorded'; record: ConversationRecord }
  | { t: 'missing' }
  | { t: 'unavailable' }
  | { t: 'full' }

export interface BuddyContext {
  knowledgeScope?: KnowledgeScope
  coordinationRunId?: string | undefined | null
  buddyId: string
  workspaceId: string
  buddyProjectId?: string | undefined | null
  legacyWorkItemId?: string | undefined | null
  automationRunId?: string | undefined | null
  delegatedByBuddyId?: string | undefined | null
  parentBuddyConversationId?: string | undefined | null
  allowedBuddyOperations?: Array<string>
}

export type BuddyVisibility = 'foreground' | 'background'

/** What `onChange` receives. */
export type ChangeEvent =
  | { t: 'changes'; rev: number; sessionIds: Array<string>; removed: Array<string> }
  | { t: 'failed'; message: string }

/** A compaction the harness recorded with its own marker record (never inferred from numbers). */
export interface Compaction {
  count: number
  /** Context just before the latest boundary (Claude only). */
  preTokens?: number
  postTokens?: number
  /** The harness's own word for why, verbatim. */
  trigger?: string
}

/**
 * The latest request's provider-counted context for a session: what the context meter shows.
 * Never a sum (usage is); the two diverge at every compaction.
 */
export interface ContextReading {
  /**
   * Claude and OpenCode: input + cache read + cache write; Codex and Muse: input (their cached
   * count is a subset of it).
   */
  contextTokens: number
  /** Codex `model_context_window`, Muse target/soft threshold. Absent: resolve from the model. */
  contextWindow?: number
  /** Absent: the harness recorded no compaction for this session. */
  compaction?: Compaction
}

export interface ConversationBranch {
  sourceConversationId: string
  throughMessageId: string
  audience: KnowledgeScope
  handoff: string
  /**
   * digest → handoff. A BTreeMap so the stored JSON is byte-stable; key order carries no
   * meaning (the TS reads it only by key and by count).
   */
  launches?: Record<string, string>
}

export interface ConversationConfig {
  provider: Provider
  model: ModelSelection
  reasoning: ReasoningSelection
}

export interface ConversationCreation {
  branch?: ConversationBranch
  commandId?: string
  fingerprint?: string
  initialMessage?: string
  initialMessageDispatchClaimedAt?: string
  initialMessageDispatchClaimToken?: string
  initialMessageDispatchedAt?: string
  swarmDebugPrefix?: string
  resumedFromConversationId?: string
}

/**
 * `ConversationKindSchema`: what the thread is, fixed at creation. The worker ids and role are
 * `.nullable()` (never absent), so they serialize as `null` — `use_nullable` makes napi do the
 * same (without it `None` crosses as an absent key, which the Zod schema rejects).
 */
export type ConversationKind =
  | { t: 'chat' }
  | { t: 'buddy'; context: BuddyContext; visibility: BuddyVisibility }
  | { t: 'builder' }
  | { t: 'worker'; swarmId: string | null; workerId: string | null; role: WorkerRole | null }

/**
 * One durable conversation record. `version` is not a field: every stored record is version 2
 * (T09's `kind`); import refuses a v1 file (run record-migration.ts on the copy first).
 */
export interface ConversationRecord {
  conversationId: string
  kind: ConversationKind
  /** Earlier sessions of this conversation, oldest first. Indexed for transcript discovery. */
  sessionBindings: Array<SessionBinding>
  /** The session a new turn resumes. Absent = no provider session started yet. */
  currentSession?: SessionBinding
  status: RecordStatus
  /** The owner marked it done: hidden from working lists, still loaded and resumable. */
  done: boolean
  workingDirectory?: string
  creation?: ConversationCreation
  deletedAt?: string
  config: ConversationConfig
  /** Advances on every write; the internal CAS token. */
  recordRevision: number
  /** Advances only when `config` changes; the client's CAS token for `set_config`. */
  configRevision: number
  lastResolvedConfig?: ResolvedExecutionConfig
  provenance: Provenance
  createdAt: string
  updatedAt: string
}

export type CreateOutcome =
  | { t: 'created'; record: ConversationRecord }
  | { t: 'exists'; current: ConversationRecord }

/** The working directory of a session and how it was learned. */
export type Cwd =
  | { t: 'transcript'; path: string }
  | { t: 'projectDir'; path: string }
  | { t: 'decoded'; path: string }
  | { t: 'unknown' }

/** The standard provider roots under `home`, including any Gemini sandbox homes that exist. */
export declare function defaultRoots(home: string): Array<Root>

export type Format = 'claude' | 'codex' | 'cursor' | 'gemini' | 'opencode' | 'muse'

/** Who a session belongs to, recovered from in-band markers (and Muse's durable creation record). */
export type Identity =
  | { t: 'general' }
  | { t: 'buddy'; buddyId: string; context: string }
  | { t: 'builder' }
  | { t: 'worker'; swarmId?: string; workerId?: string; role: WorkerRole }

/** `BuddyKnowledgeScopeSchema` (strict objects). */
export type KnowledgeScope =
  | { kind: 'owner_thread'; conversationId: string }
  | { kind: 'project'; projectId: string }
  | { kind: 'workspace'; workspaceId: string }

export interface ListOptions {
  /** Revision already seen; 0 lists everything. */
  since: number
}

export interface Message {
  /** 0-based position in the session's visible history. Stable while the file only grows. */
  seq: number
  role: Role
  /** When the message started (an assistant reply starts when the message before it did). */
  at?: number
  /** Set on assistant replies whose completion the transcript records. */
  completedAt?: number
  content: string
  toolCall?: ToolCall
}

export interface MessagesOptions {
  /** Return messages with `seq` greater than this; -1 starts at the first message. */
  afterSeq: number
  limit: number
}

export type ModelSelection =
  | { mode: 'default' }
  | { mode: 'explicit'; modelId: string }

/** `create`'s input: a record at revision 0, stamped by the store. */
export interface NewRecord {
  conversationId: string
  kind: ConversationKind
  sessionBindings: Array<SessionBinding>
  currentSession?: SessionBinding
  workingDirectory?: string
  creation?: ConversationCreation
  config: ConversationConfig
  lastResolvedConfig?: ResolvedExecutionConfig
  provenance: Provenance
}

export type Provenance = 'user' | 'legacy_inferred' | 'external_discovered'

export type Provider = 'claude' | 'codex' | 'cursor' | 'gemini' | 'opencode' | 'muse'

/** Provider-counted tokens of the latest request on one session (`ProviderTurnUsageSchema`). */
export interface ProviderTurnUsage {
  contextTokens: number
  outputTokens: number
  cachedInputTokens?: number
  cacheWriteTokens?: number
  /** Present only when the harness reports one (codex). */
  contextWindow?: number
  observedAt: string
}

export type ReasoningSelection =
  | { mode: 'default' }
  | { mode: 'disabled' }
  | { mode: 'explicit'; effort: string }

export type RecordStatus = 'active' | 'deleted'

/**
 * The startup list row: what hydration joins against ingest's session rows. The full record is
 * one `get` away.
 */
export interface RecordSummary {
  conversationId: string
  status: RecordStatus
  done: boolean
  kind: ConversationKind
  provenance: Provenance
  workingDirectory?: string
  provider: Provider
  currentSession?: SessionKey
  /** Every bound session (history and current), for the join with transcripts. */
  sessions: Array<SessionKey>
  configRevision: number
  createdAt: string
  updatedAt: string
}

export type RekeyOutcome =
  | { t: 'rekeyed'; record: ConversationRecord }
  | { t: 'missing' }
  | { t: 'exists'; current: ConversationRecord }

export interface RemovedSession {
  sessionId: string
  sourcePath: string
  rev: number
}

export interface ResolvedExecutionConfig {
  provider: Provider
  modelId: string
  reasoningEffort?: string
}

export type Role = 'user' | 'assistant' | 'system'

/** One provider root to ingest. Absent roots are reported by `start`, not guessed. */
export interface Root {
  format: Format
  path: string
}

export interface ScanReport {
  sources: number
  unchanged: number
  resumed: number
  full: number
  /** Why each full read happened (`unseen`, `rewritten`, `rebuild:Reordered`, …). */
  fullReasons: Record<string, number>
  removed: number
  failed: number
  messagesWritten: number
  bytesRead: number
  malformedLines: number
  ms: number
  errors: Array<string>
  /** Roots that do not exist; they are not watched (restart once the provider creates them). */
  missingRoots: Array<string>
  rev: number
}

/** One deep-search match. */
export interface SearchHit {
  sessionId: string
  message: Message
}

export interface SessionBinding {
  provider: Provider
  sessionId: string
  buddyAudienceKey?: string
  latestUsage?: ProviderTurnUsage
}

/** A (provider, session id) key. */
export interface SessionKey {
  provider: Provider
  sessionId: string
}

export interface SessionPage {
  /** Pass as `since` next time. */
  rev: number
  rows: Array<SessionRow>
  removed: Array<RemovedSession>
}

/** The list row for one session: everything the sidebar needs, nothing per message. */
export interface SessionRow {
  sessionId: string
  provider: Provider
  format: Format
  /** The file (a directory for OpenCode) this row was read from. */
  sourcePath: string
  cwd: Cwd
  /** The model the transcript names. `null` = none recorded (the TS `'unknown'` sentinel). */
  observedModel?: string
  /** Provider-generated title (Claude ai-title / custom-title). */
  title?: string
  /** `title`, else the first visible user text, on one line, at most 60 characters. */
  label: string
  createdAt: number
  activityAt: number
  timeFrom: TimeFrom
  messageCount: number
  /** Codex sub-agent threads name the thread that spawned them. */
  parentSessionId?: string
  identity: Identity
  /** The hidden swarm debug prefix removed from the first prompt, when there was one. */
  swarmDebugPrefix?: string
  /** Muse durable lineage for a forked chat. */
  resumedFromConversationId?: string
  usage?: Usage
  subAgents: Array<SubAgent>
  /** Store revision that last changed this row; `listSessions({ since })` pages on it. */
  rev: number
}

/** `set_config`: compare-and-set on `configRevision`. */
export interface SetConfig {
  conversationId: string
  expectedConfigRevision: number
  config: ConversationConfig
  lastResolvedConfig: ResolvedExecutionConfig
}

export type SetConfigOutcome =
  | { t: 'committed'; record: ConversationRecord }
  | { t: 'revision_conflict'; current: ConversationRecord }
  | { t: 'tombstoned'; current: ConversationRecord }
  | { t: 'missing' }

export interface SubAgent {
  id: string
  description: string
  toolUses: number
  currentAction?: string
  startedAt?: number
  completedAt?: number
}

export type TimeFrom = 'transcript' | 'fileMtime'

export interface ToolCall {
  name: string
  /** Raw input as text (pretty JSON when the arguments were JSON). Absent when none was sent. */
  input?: string
}

/**
 * Provider-reported token totals. Claude: summed per request id; Codex: the last cumulative
 * `token_count`; OpenCode: summed per assistant message. Other providers record none.
 */
export interface Usage {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
}

/**
 * Token totals of the turns in one group. Pricing stays with the caller, except the cost a
 * provider recorded itself (OpenCode), summed as `reportedCostUsd` (0 when none did).
 */
export interface UsageGroup {
  key: UsageKey
  turns: number
  /** Distinct sources with a turn in the group. */
  sessions: number
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
  reportedCostUsd: number
  firstAt: number
  lastAt: number
}

export type UsageGroupBy = 'session' | 'day' | 'model'

/** What one usage group is. */
export type UsageKey =
  | { t: 'session'; sessionId: string; sourcePath: string; provider: Provider; format: Format; model?: string }
  | { t: 'day'; day: string }
  | { t: 'model'; provider: Provider; model?: string }

/**
 * A usage query: turns whose transcript time is in `[since, until)` (epoch ms). `since` is
 * required: every query is a range on the turn-time index, never a scan of all turns.
 */
export interface UsageQuery {
  since: number
  until?: number
  groupBy: UsageGroupBy
}

export interface UsageReport {
  groups: Array<UsageGroup>
  /**
   * The latest Codex `rate_limits` payload (raw JSON) of the most recently active session that
   * recorded one; `/api/usage` shows it as the Codex limits.
   */
  codexRateLimits?: string
}

export type WorkerRole = 'work' | 'review' | 'fix'
