/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class Ingest {
  /**
   * Open (or create) the store at `dbPath`, bring it up to date with `roots`, and watch them.
   * Resolves after the initial scan is committed; `onChange` also fires during that scan.
   */
  static start(roots: Array<Root>, dbPath: string, onChange: ((arg: ChangeEvent) => void)): Promise<Ingest>
  /** The initial scan's counts and timing. */
  get initialScan(): ScanReport
  listSessions(options: ListOptions): Promise<SessionPage>
  session(sessionId: string): Promise<SessionRow | null>
  messages(sessionId: string, options: MessagesOptions): Promise<Array<Message>>
  /** Stop watching and release `onChange` (so Node can exit). Idempotent. */
  stop(): Promise<void>
}

/** What `onChange` receives. */
export type ChangeEvent =
  | { t: 'changes'; rev: number; sessionIds: Array<string>; removed: Array<string> }
  | { t: 'failed'; message: string }

/** The working directory of a session and how it was learned. */
export type Cwd =
  | { t: 'transcript'; path: string }
  | { t: 'projectDir'; path: string }
  | { t: 'decoded'; path: string }
  | { t: 'unknown' }

/** The standard provider roots under `home`, including any Gemini sandbox homes that exist. */
export declare function defaultRoots(home: string): Array<Root>

export type Format = 'claude' | 'codex' | 'cursor' | 'gemini' | 'opencode' | 'muse'

/** Who a session belongs to, recovered from in-band markers (and Muse's durable creation record). */
export type Identity =
  | { t: 'general' }
  | { t: 'buddy'; buddyId: string; context: string }
  | { t: 'builder' }
  | { t: 'worker'; swarmId?: string; workerId?: string; role: WorkerRole }

export interface ListOptions {
  /** Revision already seen; 0 lists everything. */
  since: number
}

export interface Message {
  /** 0-based position in the session's visible history. Stable while the file only grows. */
  seq: number
  role: Role
  /** When the message started (an assistant reply starts when the message before it did). */
  at?: number
  /** Set on assistant replies whose completion the transcript records. */
  completedAt?: number
  content: string
  toolCall?: ToolCall
}

export interface MessagesOptions {
  /** Return messages with `seq` greater than this; -1 starts at the first message. */
  afterSeq: number
  limit: number
}

export type Provider = 'claude' | 'codex' | 'cursor' | 'gemini' | 'opencode' | 'muse'

export interface RemovedSession {
  sessionId: string
  sourcePath: string
  rev: number
}

export type Role = 'user' | 'assistant' | 'system'

/** One provider root to ingest. Absent roots are reported by `start`, not guessed. */
export interface Root {
  format: Format
  path: string
}

export interface ScanReport {
  sources: number
  unchanged: number
  resumed: number
  full: number
  /** Why each full read happened (`unseen`, `rewritten`, `rebuild:Reordered`, …). */
  fullReasons: Record<string, number>
  removed: number
  failed: number
  messagesWritten: number
  bytesRead: number
  malformedLines: number
  ms: number
  errors: Array<string>
  /** Roots that do not exist; they are not watched (restart once the provider creates them). */
  missingRoots: Array<string>
  rev: number
}

export interface SessionPage {
  /** Pass as `since` next time. */
  rev: number
  rows: Array<SessionRow>
  removed: Array<RemovedSession>
}

/** The list row for one session: everything the sidebar needs, nothing per message. */
export interface SessionRow {
  sessionId: string
  provider: Provider
  format: Format
  /** The file (a directory for OpenCode) this row was read from. */
  sourcePath: string
  cwd: Cwd
  /** The model the transcript names. `null` = none recorded (the TS `'unknown'` sentinel). */
  observedModel?: string
  /** Provider-generated title (Claude ai-title / custom-title). */
  title?: string
  /** `title`, else the first visible user text, on one line, at most 60 characters. */
  label: string
  createdAt: number
  activityAt: number
  timeFrom: TimeFrom
  messageCount: number
  /** Codex sub-agent threads name the thread that spawned them. */
  parentSessionId?: string
  identity: Identity
  /** The hidden swarm debug prefix removed from the first prompt, when there was one. */
  swarmDebugPrefix?: string
  /** Muse durable lineage for a forked chat. */
  resumedFromConversationId?: string
  usage?: Usage
  subAgents: Array<SubAgent>
  /** Store revision that last changed this row; `listSessions({ since })` pages on it. */
  rev: number
}

export interface SubAgent {
  id: string
  description: string
  toolUses: number
  currentAction?: string
  startedAt?: number
  completedAt?: number
}

export type TimeFrom = 'transcript' | 'fileMtime'

export interface ToolCall {
  name: string
  /** Raw input as text (pretty JSON when the arguments were JSON). Absent when none was sent. */
  input?: string
}

/**
 * Provider-reported token totals. Claude: summed per request id; Codex: the last cumulative
 * `token_count`; OpenCode: summed per assistant message. Other providers record none.
 */
export interface Usage {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
}

export type WorkerRole = 'work' | 'review' | 'fix'
