/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class BuddiesCore {
  /** Opens (or creates) the database. Refuses a file that is not a buddies-core database. */
  static open(path: string): Promise<BuddiesCore>
  authorize(actor: Actor, op: Op, subject: Subject): Promise<Decision>
  post(actor: Actor, input: PostInput): Promise<Post>
  reply(actor: Actor, input: ReplyInput): Promise<Post>
  listPosts(query: PostQuery, before: Cursor | undefined | null, limit: number): Promise<PostPage>
  inbox(actor: Actor, workspaceId: string): Promise<Inbox>
  markRead(actor: Actor, channelId: string, postId: string): Promise<void>
  createChannel(actor: Actor, input: ChannelInput): Promise<Channel>
  listChannels(workspaceId: string): Promise<Array<Channel>>
  readDoc(actor: Actor, doc: DocRef): Promise<Doc | null>
  writeDoc(actor: Actor, input: DocWrite): Promise<Doc>
  listDocs(actor: Actor, buddyId: string, kind: DocKind): Promise<Array<Doc>>
  docRevisions(actor: Actor, docId: string): Promise<Array<DocRevision>>
  upsertTask(actor: Actor, write: TaskWrite): Promise<Task>
  getTask(id: string): Promise<Task>
  listTasks(query: TaskQuery): Promise<Array<Task>>
  enqueueRun(actor: Actor, input: EnqueueInput): Promise<Run>
  claimRun(leaseMs: number): Promise<Claim | null>
  settleRun(runId: string, leaseToken: string, outcome: Outcome): Promise<Run>
  bindRun(runId: string, leaseToken: string, conversationId: string): Promise<Run>
  cancelRun(actor: Actor, runId: string): Promise<Run>
  getRun(id: string): Promise<Run>
  listRuns(query: RunQuery, limit: number): Promise<Array<Run>>
  putSchedule(actor: Actor, input: ScheduleInput): Promise<Schedule>
  listSchedules(buddyId: string): Promise<Array<Schedule>>
  dueSchedules(now: string): Promise<Array<Run>>
  appendEvent(actor: Actor, input: EventInput): Promise<Event>
  pruneEvents(before: string): Promise<number>
  listEvents(buddyId: string, beforeSeq: number, limit: number): Promise<Array<Event>>
  listWorkspaces(): Promise<Array<Workspace>>
  getBuddy(id: string): Promise<Buddy>
  listBuddies(workspaceId: string): Promise<Array<Buddy>>
  bindConversation(actor: Actor, input: ConversationInput): Promise<Conversation>
  getConversation(id: string): Promise<Conversation | null>
}

/** Who acts. Stored as NULL (post author / channel creator) or the key `'owner'` (events, read cursors). */
export type Actor =
  | { kind: 'owner' }
  | { kind: 'buddy'; id: string }

export interface Buddy {
  id: string
  workspaceId: string
  slug: string
  name: string
  role: string
  status: BuddyStatus
  managerId?: string
  provider?: string
  model?: string
  reasoningEffort?: string
  soulPath?: string
  backgroundEnabled: boolean
  maxActiveRuns: number
  createdAt: string
}

export type BuddyStatus = 'active' | 'archived'

export interface Channel {
  id: string
  workspaceId: string
  name: string
  purpose: string
  createdBy: Actor
  createdAt: string
}

export interface ChannelInput {
  workspaceId: string
  name: string
  purpose: string
  key: string
}

export interface ChannelUnread {
  channelId: string
  name: string
  unread: number
}

export interface Claim {
  run: Run
  leaseToken: string
}

export interface Conversation {
  id: string
  buddyId: string
  workspaceId: string
  taskId?: string
  createdAt: string
}

export interface ConversationInput {
  id: string
  buddyId: string
  taskId?: string
}

/** Keyset position: posts strictly older than (created_at, id). */
export interface Cursor {
  createdAt: string
  id: string
}

export type Decision =
  | { kind: 'allowed' }
  | { kind: 'denied'; reason: string }

export interface Doc {
  id: string
  buddyId: string
  workspaceId: string
  scope: DocScope
  kind: DocKind
  name: string
  revision: number
  content: string
  updatedAt: string
}

export type DocKind = 'soul' | 'working' | 'long_term' | 'note' | 'shared'

export interface DocRef {
  buddyId: string
  scope: DocScope
  kind: DocKind
  name: string
}

export interface DocRevision {
  docId: string
  revision: number
  content: string
  reason: string
  author: string
  provenance: string
  sha256: string
  createdAt: string
}

/** Doc audience. Columns (scope_kind, scope_id); Buddy scope's id is the buddy, Workspace's the workspace. */
export type DocScope =
  | { kind: 'buddy' }
  | { kind: 'workspace'; workspaceId: string }
  | { kind: 'task'; taskId: string }
  | { kind: 'thread'; threadId: string }

export interface DocWrite {
  doc: DocRef
  content: string
  /** The revision the writer read; 0 when the doc does not exist yet. */
  baseRevision: number
  reason: string
  key: string
}

export interface EnqueueInput {
  buddyId: string
  input: RunInput
  conversationId?: string
  taskId?: string
  afterRunId?: string
  deadline?: string
}

export interface Event {
  seq: number
  at: string
  actor: string
  workspaceId: string
  buddyId?: string
  taskId?: string
  op: string
  payload: string
  idemKey?: string
  resultRef?: string
}

export interface EventInput {
  workspaceId: string
  op: string
  payload: string
  key?: string
  buddyId?: string
  taskId?: string
}

export interface Inbox {
  /** Requests addressed to the actor that still await its reply. */
  requests: Array<Post>
  /** The actor's own requests still awaiting someone else's reply. */
  waitingOn: Array<Post>
  unread: Array<ChannelUnread>
}

export type Op = 'read_doc' | 'write_doc' | 'post' | 'reply' | 'write_task' | 'enqueue_run' | 'cancel_run' | 'write_schedule' | 'admin'

/** How a run ended, reported by the runner. */
export type Outcome =
  | { kind: 'complete'; text: string }
  | { kind: 'failed'; code: string; error: string }
  | { kind: 'cancelled'; reason: string }

export interface Post {
  id: string
  workspaceId: string
  author: Actor
  target: Target
  rootId?: string
  replyToId?: string
  taskId?: string
  purpose?: string
  body: string
  evidence: Array<string>
  reply: Reply
  conversationId?: string
  returnConversationId?: string
  createdAt: string
}

export interface PostInput {
  target: Target
  kind: PostKind
  body: string
  purpose?: string
  evidence: Array<string>
  /** Reply inside a thread: the post being answered. Absent = a new top-level post. */
  replyToId?: string
  taskId?: string
  /** The sender's conversation; a `Request`'s reply returns there. */
  fromConversationId?: string
  key: string
}

export type PostKind = 'inform' | 'request'

export interface PostPage {
  posts: Array<Post>
  next?: Cursor
}

export type PostQuery =
  | { kind: 'channel'; channelId: string }
  | { kind: 'thread'; rootId: string }
  | { kind: 'task'; taskId: string }
  | { kind: 'to'; target: Target }
  | { kind: 'from'; author: Actor }

/** A post's reply lifecycle. `reply_state` NULL is `NotOwed`. */
export type Reply =
  | { state: 'not_owed' }
  | { state: 'awaiting' }
  | { state: 'replied'; body: string; evidence: Array<string>; repliedAt: string }
  | { state: 'cancelled' }
  | { state: 'failed' }

export interface ReplyInput {
  postId: string
  body: string
  evidence: Array<string>
  key: string
}

export interface Run {
  id: string
  inputKey: string
  attempt: number
  input: RunInput
  buddyId: string
  workspaceId: string
  conversationId?: string
  taskId?: string
  taskEpoch?: number
  afterRunId?: string
  retryOf?: string
  status: RunStatus
  deadline?: string
  leaseExpiresAt?: string
  snapshot?: string
  outcome?: string
  errorCode?: string
  error?: string
  readyAt: string
  createdAt: string
  startedAt?: string
  endedAt?: string
}

/** Why a run exists. Columns: (input_kind, input_id); the input_key is derived from it. */
export type RunInput =
  | { kind: 'chat'; turnId: string }
  | { kind: 'post'; postId: string }
  | { kind: 'reply'; postId: string }
  | { kind: 'schedule'; scheduleId: string; slot: string }
  | { kind: 'failure_notice'; runId: string }

export type RunQuery =
  | { kind: 'buddy'; buddyId: string }
  | { kind: 'conversation'; conversationId: string }
  | { kind: 'task'; taskId: string }
  | { kind: 'queued' }

export type RunStatus = 'queued' | 'running' | 'cancel_requested' | 'complete' | 'failed' | 'cancelled'

export interface Schedule {
  id: string
  buddyId: string
  workspaceId: string
  taskId?: string
  name: string
  cron: string
  timezone: string
  prompt: string
  limits: string
  enabled: boolean
  nextRunAt?: string
  archivedAt?: string
  createdAt: string
}

export interface ScheduleInput {
  /** Absent = create. */
  id?: string
  buddyId: string
  taskId?: string
  name: string
  cron: string
  timezone: string
  prompt: string
  limits: string
  enabled: boolean
  key: string
}

/** Whose resource an operation touches (the `target` of `authorize`). */
export type Subject =
  | { kind: 'owner' }
  | { kind: 'buddy'; id: string }

/** Where a post is addressed. Columns: (target_kind, target_id), target_id NULL for the owner. */
export type Target =
  | { kind: 'buddy'; id: string }
  | { kind: 'owner' }
  | { kind: 'channel'; id: string }
  | { kind: 'task'; id: string }

export interface Task {
  id: string
  workspaceId: string
  ownerId: string
  parentId?: string
  title: string
  doneCriteria: string
  status: TaskStatus
  paused: boolean
  epoch: number
  nextAction?: string
  blockedReason?: string
  evidence: Array<string>
  position: number
  revision: number
  createdAt: string
  updatedAt: string
}

export interface TaskChanges {
  title?: string
  doneCriteria?: string
  status?: TaskStatus
  nextAction?: string
  blockedReason?: string
  evidence?: Array<string>
  paused?: boolean
  position?: number
  ownerId?: string
}

export type TaskQuery =
  | { kind: 'owner'; buddyId: string }
  | { kind: 'workspace'; workspaceId: string }
  | { kind: 'children'; parentId: string }

export type TaskStatus = 'open' | 'in_progress' | 'blocked' | 'review' | 'done' | 'cancelled'

/** A task write. Every field of `TaskChanges` is a patch: absent = unchanged. */
export type TaskWrite =
  | { kind: 'create'; ownerId: string; parentId?: string; title: string; doneCriteria: string; key: string }
  | { kind: 'update'; taskId: string; baseRevision: number; changes: TaskChanges; key: string }

export interface Workspace {
  id: string
  name: string
  rootPath: string
  createdAt: string
}
