/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class BuddiesCore {
  /** Opens (or creates) the database. Refuses a file that is not a buddies-core database. */
  static open(path: string): Promise<BuddiesCore>
  authorize(actor: Actor, op: Op, subject: Subject): Promise<Decision>
  post(actor: Actor, channel: ChannelRef, input: PostInput): Promise<Post>
  answer(actor: Actor, input: AnswerInput): Promise<Post>
  getPost(actor: Actor, id: string): Promise<Post>
  openChannel(actor: Actor, channel: ChannelRef): Promise<Channel>
  listPosts(actor: Actor, query: PostQuery, before: Cursor | undefined | null, limit: number): Promise<PostPage>
  listPostsFrom(actor: Actor, query: PostQuery, postId: string, limit: number): Promise<PostPage>
  threadStats(actor: Actor, channelId: string, rootIds: Array<string>): Promise<Array<ThreadStat>>
  taskPosts(actor: Actor, taskId: string, before: Cursor | undefined | null, limit: number): Promise<PostPage>
  searchPosts(actor: Actor, workspaceId: string, query: string, limit: number): Promise<Array<Post>>
  inbox(actor: Actor, workspaceId: string): Promise<Inbox>
  markRead(actor: Actor, channelId: string, postId: string): Promise<void>
  createChannel(actor: Actor, input: ChannelInput): Promise<Channel>
  listChannels(workspaceId: string): Promise<Array<Channel>>
  readDoc(actor: Actor, doc: DocRef): Promise<Doc | null>
  writeDoc(actor: Actor, input: DocWrite): Promise<Doc>
  listDocs(actor: Actor, buddyId: string, kind: DocKind): Promise<Array<Doc>>
  docRevisions(actor: Actor, docId: string): Promise<Array<DocRevision>>
  upsertTask(actor: Actor, write: TaskWrite): Promise<Task>
  getTask(id: string): Promise<Task>
  listTasks(query: TaskQuery): Promise<Array<Task>>
  taskCounts(workspaceId: string): Promise<Array<TaskCount>>
  enqueueRun(actor: Actor, input: EnqueueInput): Promise<Run>
  claimRun(leaseMs: number): Promise<Claim | null>
  settleRun(runId: string, leaseToken: string, outcome: Outcome): Promise<Run>
  bindRun(runId: string, leaseToken: string, conversationId: string): Promise<Run>
  cancelRun(actor: Actor, runId: string): Promise<Run>
  recoverRuns(): Promise<Recovery>
  createWorkspace(actor: Actor, input: WorkspaceInput): Promise<Workspace>
  createBuddy(actor: Actor, input: BuddyCreate): Promise<Buddy>
  updateBuddy(actor: Actor, input: BuddyUpdate): Promise<Buddy>
  getRun(id: string): Promise<Run>
  listRuns(query: RunQuery, limit: number): Promise<Array<Run>>
  putSchedule(actor: Actor, input: ScheduleInput): Promise<Schedule>
  listSchedules(buddyId: string): Promise<Array<Schedule>>
  dueSchedules(now: string): Promise<Array<Run>>
  appendEvent(actor: Actor, input: EventInput): Promise<Event>
  pruneEvents(before: string): Promise<number>
  listEvents(buddyId: string, beforeSeq: number, limit: number): Promise<Array<Event>>
  listWorkspaces(): Promise<Array<Workspace>>
  getBuddy(id: string): Promise<Buddy>
  listBuddies(workspaceId: string): Promise<Array<Buddy>>
  bindConversation(actor: Actor, input: ConversationInput): Promise<Conversation>
  getConversation(id: string): Promise<Conversation | null>
}

/**
 * Who acts. Stored as NULL (post author / channel creator) or the key `'owner'` (events, read
 * cursors, channel members).
 */
export type Actor =
  | { kind: 'owner' }
  | { kind: 'buddy'; id: string }

export interface AnswerInput {
  requestId: string
  body: string
  evidence: Array<string>
  key: string
}

export interface Buddy {
  id: string
  workspaceId: string
  slug: string
  name: string
  role: string
  status: BuddyStatus
  managerId?: string
  provider?: string
  model?: string
  reasoningEffort?: string
  soulPath?: string
  backgroundEnabled: boolean
  maxActiveRuns: number
  createdAt: string
}

/** A patch: every absent field is unchanged. */
export interface BuddyChanges {
  name?: string
  role?: string
  manager?: ManagerRef
  provider?: Setting
  model?: Setting
  reasoningEffort?: Setting
  backgroundEnabled?: boolean
  maxActiveRuns?: number
  status?: BuddyStatus
}

export interface BuddyCreate {
  workspaceId: string
  slug: string
  name: string
  role: string
  manager: ManagerRef
  provider?: string
  model?: string
  reasoningEffort?: string
  /** Whether requests and schedules may start its turns (off: they wait, queued). */
  backgroundEnabled: boolean
  key: string
}

export type BuddyStatus = 'active' | 'archived'

export interface BuddyUpdate {
  buddyId: string
  changes: BuddyChanges
  key: string
}

export interface Channel {
  id: string
  workspaceId: string
  kind: ChannelKind
  createdBy: Actor
  createdAt: string
}

export interface ChannelInput {
  workspaceId: string
  name: string
  purpose: string
  key: string
}

/** What a channel is. Columns: `kind` plus (name, purpose) | member_key | task_id. */
export type ChannelKind =
  | { type: 'public'; name: string; purpose: string }
  | { type: 'direct'; members: Array<Actor> }
  | { type: 'task'; taskId: string }

/** Where a post goes. A direct or task channel is found, or created on first use. */
export type ChannelRef =
  | { kind: 'id'; id: string }
  | { kind: 'direct'; members: Array<Actor> }
  | { kind: 'task'; taskId: string }

export interface ChannelUnread {
  channel: Channel
  /** Posts by others after the reader's cursor (all of them when it has none). */
  unread: number
  /** The reader's cursor: the ordered id it has read through. Absent: it never read the channel. */
  lastReadOrd?: string
}

export interface Claim {
  run: Run
  leaseToken: string
}

export interface Conversation {
  id: string
  buddyId: string
  workspaceId: string
  taskId?: string
  createdAt: string
}

export interface ConversationInput {
  id: string
  buddyId: string
  taskId?: string
}

/** Keyset position: posts strictly older than this ordered id. */
export interface Cursor {
  /** The ordered id of the last post of the previous page. */
  ord: string
}

export type Decision =
  | { kind: 'allowed' }
  | { kind: 'denied'; reason: string }

export interface Doc {
  id: string
  buddyId: string
  workspaceId: string
  scope: DocScope
  kind: DocKind
  name: string
  revision: number
  content: string
  updatedAt: string
}

export type DocKind = 'soul' | 'working' | 'long_term' | 'shared'

export interface DocRef {
  buddyId: string
  scope: DocScope
  kind: DocKind
  name: string
}

export interface DocRevision {
  docId: string
  revision: number
  content: string
  reason: string
  author: string
  provenance: string
  sha256: string
  createdAt: string
}

/**
 * Doc audience. Columns (scope_kind, scope_id); Buddy scope's id is the buddy, Workspace's the workspace.
 * Memory kinds (soul, working, long_term) are always Buddy-scoped: one per Buddy, read by every
 * turn kind and the owner's Memory tab. Only shared docs may be Workspace-scoped.
 */
export type DocScope =
  | { kind: 'buddy' }
  | { kind: 'workspace'; workspaceId: string }

export interface DocWrite {
  doc: DocRef
  content: string
  /** The revision the writer read; 0 when the doc does not exist yet. */
  baseRevision: number
  reason: string
  key: string
}

export interface EnqueueInput {
  buddyId: string
  input: RunInput
  conversationId?: string
  taskId?: string
  afterRunId?: string
  deadline?: string
}

export interface Event {
  seq: number
  at: string
  actor: string
  workspaceId: string
  buddyId?: string
  taskId?: string
  op: string
  payload: string
  idemKey?: string
  resultRef?: string
}

export interface EventInput {
  workspaceId: string
  op: string
  payload: string
  key?: string
  buddyId?: string
  taskId?: string
}

export interface Inbox {
  /** Requests addressed to the actor that still await its answer. */
  requests: Array<Post>
  /** The actor's own requests still awaiting someone else's answer. */
  waitingOn: Array<Post>
  /** The actor's channels in the workspace: every public one, its direct ones, and any it has read. */
  channels: Array<ChannelUnread>
}

/** Who a buddy reports to. `Nobody` makes it a top-level buddy. */
export type ManagerRef =
  | { kind: 'nobody' }
  | { kind: 'buddy'; id: string }

export type Op = 'read_doc' | 'write_doc' | 'post' | 'read_channel' | 'search_posts' | 'create_channel' | 'write_task' | 'enqueue_run' | 'cancel_run' | 'write_schedule' | 'admin'

/** How a run ended, reported by the runner. */
export type Outcome =
  | { kind: 'complete'; text: string }
  | { kind: 'failed'; code: string; error: string }
  | { kind: 'cancelled'; reason: string }

export interface Post {
  id: string
  channelId: string
  author: Actor
  rootId?: string
  replyToId?: string
  taskId?: string
  purpose?: string
  body: string
  evidence: Array<string>
  request: RequestState
  conversationId?: string
  returnConversationId?: string
  createdAt: string
  /** The post's ordered id (UUIDv7): threads, pages and read cursors order by it. */
  ord: string
}

export interface PostInput {
  /** `Request` needs a direct channel: the other members owe the answer. */
  kind: PostKind
  body: string
  purpose?: string
  evidence: Array<string>
  /** A reply in a thread: the post it responds to, in the same channel. Absent = a new top-level post. */
  replyToId?: string
  taskId?: string
  /** The sender's conversation; a `Request`'s answer returns there. */
  fromConversationId?: string
  key: string
}

export type PostKind = 'inform' | 'request'

export interface PostPage {
  posts: Array<Post>
  next?: Cursor
}

export type PostQuery =
  | { kind: 'channel'; channelId: string }
  | { kind: 'thread'; rootId: string }

/** What startup recovery ended: runs a dead process held, and chat turns nobody waits for. */
export interface Recovery {
  interrupted: number
  abandonedChats: number
}

/** A post's request lifecycle. Column `request` NULL is `None`; `Answered` names the answer post. */
export type RequestState =
  | { state: 'none' }
  | { state: 'awaiting' }
  | { state: 'answered'; answerId: string }
  | { state: 'cancelled' }
  | { state: 'failed' }

export interface Run {
  id: string
  inputKey: string
  attempt: number
  input: RunInput
  buddyId: string
  workspaceId: string
  conversationId?: string
  taskId?: string
  taskEpoch?: number
  afterRunId?: string
  retryOf?: string
  status: RunStatus
  deadline?: string
  leaseExpiresAt?: string
  snapshot?: string
  outcome?: string
  errorCode?: string
  error?: string
  readyAt: string
  createdAt: string
  startedAt?: string
  endedAt?: string
}

/** Why a run exists. Columns: (input_kind, input_id); the input_key is derived from it. */
export type RunInput =
  | { kind: 'chat'; turnId: string }
  | { kind: 'post'; postId: string }
  | { kind: 'reply'; postId: string }
  | { kind: 'schedule'; scheduleId: string; slot: string }
  | { kind: 'failure_notice'; runId: string }

export type RunQuery =
  | { kind: 'buddy'; buddyId: string }
  | { kind: 'conversation'; conversationId: string }
  | { kind: 'task'; taskId: string }
  | { kind: 'queued' }
  | { kind: 'live'; workspaceId: string }

export type RunStatus = 'queued' | 'running' | 'cancel_requested' | 'complete' | 'failed' | 'cancelled'

export interface Schedule {
  id: string
  buddyId: string
  workspaceId: string
  taskId?: string
  name: string
  cron: string
  timezone: string
  prompt: string
  limits: string
  enabled: boolean
  nextRunAt?: string
  archivedAt?: string
  createdAt: string
}

export interface ScheduleInput {
  /** Absent = create. */
  id?: string
  buddyId: string
  taskId?: string
  name: string
  cron: string
  timezone: string
  prompt: string
  limits: string
  enabled: boolean
  key: string
}

/**
 * A profile field's new value: a named choice, or back to the server's default (column NULL).
 * A plain `Option<String>` patch could not say "clear" — absent already means "unchanged".
 */
export type Setting =
  | { kind: 'set'; value: string }
  | { kind: 'default' }

/** Whose resource an operation touches (the `target` of `authorize`). */
export type Subject =
  | { kind: 'owner' }
  | { kind: 'buddy'; id: string }
  | { kind: 'channel'; id: string }

export interface Task {
  id: string
  workspaceId: string
  ownerId: string
  parentId?: string
  title: string
  doneCriteria: string
  status: TaskStatus
  paused: boolean
  epoch: number
  nextAction?: string
  blockedReason?: string
  evidence: Array<string>
  position: number
  revision: number
  createdAt: string
  updatedAt: string
}

export interface TaskChanges {
  title?: string
  doneCriteria?: string
  status?: TaskStatus
  nextAction?: string
  blockedReason?: string
  evidence?: Array<string>
  paused?: boolean
  position?: number
  ownerId?: string
}

/** One Buddy's unfinished top-level tasks: `open` counts every one (blocked included). */
export interface TaskCount {
  buddyId: string
  open: number
  blocked: number
}

export type TaskQuery =
  | { kind: 'owner'; buddyId: string }
  | { kind: 'workspace'; workspaceId: string }
  | { kind: 'children'; parentId: string }

export type TaskStatus = 'open' | 'in_progress' | 'blocked' | 'review' | 'done' | 'cancelled'

/** A task write. Every field of `TaskChanges` is a patch: absent = unchanged. */
export type TaskWrite =
  | { kind: 'create'; ownerId: string; parentId?: string; title: string; doneCriteria: string; key: string }
  | { kind: 'update'; taskId: string; baseRevision: number; changes: TaskChanges; key: string }

/** A thread root's replies at a glance: the channel row's "3 replies · last reply 2m ago". */
export interface ThreadStat {
  rootId: string
  replies: number
  lastReplyAt: string
  /** The newest reply's ordered id: after the reader's cursor, the thread has something new. */
  lastReplyOrd: string
  lastReplyAuthor: Actor
}

export interface Workspace {
  id: string
  name: string
  rootPath: string
  createdAt: string
}

export interface WorkspaceInput {
  name: string
  rootPath: string
}
